### ISSUE TITLE
Light not turning on / off

### ISSUE THREAD

**Issue by MarcE85** [Petro31/ad_toggle_light#1]
Hey,

I've tried to toggle my light with a Shelly switch but its not working:

```
livingroom_toggle:
  module: toggle_light
  class: ToggleLight
  entity: light.shelly_shsw_pm_76dbeb
  entities:
    - light.wohnzimmer_deckenlicht
```

Did i miss something in my configuration?

Regards Marc
